<html>
<head>
    <meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>
<style type="text/css">
	table {
		font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
		width: 100%;
		border-collapse: collapse;
	}

	td, th {
		font-size: 1em;
		border: 1px solid #5B4A42;
		padding: 3px 7px 2px 7px;
	}

	th {
		font-size: 1.1em;
		text-align: center;
		padding-top: 5px;
		padding-bottom: 4px;
		background-color: #24A9E1;
		color: #ffffff;
	}
</style>
<body>
<div id="saHistoryData">
	<table id="saTable">
		<tr>
			<th>Name</th>
			<th>Age</th>
			<th>Phone</th>
		</tr>
		<#list users as user>
			<tr>
				<td>${user.name}</td>
				<td>${user.age}</td>
				<td>${user.phone}</td>
			</tr>
		</#list>
	</table>
</div>
<br/>
此邮件由系统自动生成，请勿回复!<br/>
This message is automatically generated by the system, please do not reply!
</body>
</html>
<script type="text/javascript">
	// 设置table第一行字体颜色为红色
	window.onload = function() {
		// 获取需要操作的表格
		var table = document.getElementById("saTable");
		var rows = table.getElementsByTagName("tr");
		// 循环表格行
		for (var i = 0; i < rows.length; i++) {
			var cells = rows[i].getElementsByTagName("td");
			if (i == 1) {
				for (var c = 0; c < cells.length; c++) {
					rows[i].style.color = "#f00";
				}
				break;
			}
		}
	}
</script>