<html>
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>

<body>

Dear all,

Here comes the list of sample(s) taking effective today, please be noted, thanks.

<#list itemGroups as item>
	<table style="border-spacing: 0;border: 1px solid #333;border-collapse: collapse;font-size: 12px;">
		<tr style="height: 30px;text-align: center;">
			<th>ODM</th>
			<th>项目名</th>
			<th>样品编号</th>
			<th>样品属性</th>
			<th>部件</th>
			<th>部件良率</th>
			<th>颜色</th>
			<th>缺陷名称</th>
			<th>缺陷描述</th>
			<th>缺陷不良率</th>
			<th>PE签样人</th>
			<th>CXD签样人</th>
			<th>PQM签样人</th>
			<th>Other签样人</th>
			<th>签样日期</th>
			<th>分发工厂</th>
			<th>有效期</th>
			<th>存档时间</th>
		</tr>
		<tr style="height: 30px;text-align: left;">
			<td>${info.supplier_name}</td>
			<td>${item.project}</td>
			<td>${item.sample_id}</td>
			<td>${item.sample_type}</td>
			<td>${info.part}</td>
			<td>${info.fpy}</td>
			<td>${info.color}</td>
			<td>${info.bug_name}</td>
			<td>${info.bug_desc}</td>
			<td>${info.ratio}</td>
			<td>${item.sample_sign_pe}</td>
			<td>${item.sample_sign_cxd}</td>
			<td>${item.sample_sign_pqm}</td>
			<td>${item.sample_sign_other}</td>
			<td>${item.sample_sign_date}</td>
			<td>${item.factory}</td>
			<td>${info.expiration_type}</td>
			<td>存档时间</td>
		</tr>
	</table>
	<br/><br/>
</#list>

<br/>
此邮件由系统自动生成，请勿回复!<br/>
This message is automatically generated by the system, please do not reply!
</body>
</html>