<html>
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8">
</head>

<body>

Dear all,

Here comes the list of sample(s) taking effective today, please be noted, thanks.

<#-- 获取map中所有的key -->

获取到的供应商名称 : <br>

<#list itemGroups?keys as supplierName>
		供应商名称: ${supplierName} <br>
	<#list itemGroups[supplierName]?keys as sampleCategory>
		Sample Category: ${sampleCategory}  <br>
		<#list itemGroups[supplierName][sampleCategory] as item>
			${item.sample_id} <br>
		</#list>
	</#list>
	<br>
	<br>
</#list>

<br/>
此邮件由系统自动生成，请勿回复!<br/>
This message is automatically generated by the system, please do not reply!
</body>
</html>