server:
  port: 8082

spring:
#  数据库配置
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/activiti-demo?useUnicode=true&nullCatalogMeansCurrent=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#activiti配置
  activiti:
    database-schema-update: true
    check-process-definitions: false
    #history-level: full
    #activiti7 添加这个配置，才会生成25张表，否则只有17张
    #activiti6可以不添加，但是第一次启动只有16张表，启动两次才有26张表
    #db-history-used: true

# 静态文件配置
  resources:
    static-locations: /static/**

#配置日志
logging:
  config: classpath:logging-config.xml
  level:
    org.springframework.boot.autoconfigure: ERROR

# mybatis的xml查询文件和实体类位置配置
mybatis:
  mapper-locations: classpath*:mappers/*.xml
  type-aliases-package: com.neimeng.workflow.entity.pojo

